### ISSUE TITLE
Can't extract file with error

### ISSUE THREAD

**Issue by HoDuyQuang** [rekka/unzip-jp#1]
> Traceback (most recent call last):
>   File "unzip-jp.py", line 49, in <module>
>     with open(filename, 'w') as dest:
> IOError: [Errno 13] Permission denied: 'filename\\path'

I run it using Windows 10 64bit, using python 2.7

**Comment by rekka** [comment]
Thanks for the report. Unfortunately, I do not have a Windows machine to test this on, I used to use this only on Linux and macOS. If you manage to find a solution, I definitely welcome a pull request.

**Comment by mcpower** [comment]
@HoDuyQuang I've just submitted a pull request (#2) which should fix that error - let us know whether it works for you!

**Comment by HoDuyQuang** [comment]
@mcpower Thanks for your help. It now can extract a few file, but still got an error :
Traceback (most recent call last):

>   File "unzip-jp.py", line 45, in <module>
>     uf = codecs.decode(bad_filename, 'shift_jisx0213')
> UnicodeDecodeError: 'shift_jisx0213' codec can't decode bytes in position 11-12: illegal multibyte sequence

**Comment by mcpower** [comment]
Can you print out the `repr` or the bad filename you've been having trouble with? Put `print(repr(bad_filename))` between [these two lines](https://github.com/mcpower/unzip-jp/blob/b685458583ff8e74a7d9b41b4cc33b8a9564302c/unzip-jp.py#L41-L42) and it should print it out right before it crashes.

**Comment by HoDuyQuang** [comment]
It show the last file name : 
>'20180126/\x83\x8a\x83/\x81[\x83X\x83f\x81[\x83^\x8d\xb7\x82\xb5\x91\xd6\x82\xa6\x8a\xd6\x98A\x8e\x91\x97\xbf/'

 Do you have any idea?

**Comment by mcpower** [comment]
Are you using Python 3? If so, it could be a problem with how I decode the filename into bytes. If you are, try printing out the `repr` between [these two lines](https://github.com/mcpower/unzip-jp/blob/b685458583ff8e74a7d9b41b4cc33b8a9564302c/unzip-jp.py#L37-L38) instead.

**Comment by HoDuyQuang** [comment]
No, I'm using Python 2.7. I also post in StackOverFlow here : https://stackoverflow.com/questions/49358708/decode-japanese-character-of-file-name-when-unzip. May it give some idea

**Comment by lxhg** [comment]
Hey, just hit same problem (probably?). In my case my zip file was in cp932, with minimal edits i made it work. Just loop over another 'try' block in exception of default encoding. There is a lot of japan encodings https://docs.python.org/3/library/codecs.html#standard-encodings . Try them all and see which would work/get best result. I know it is 4 years too late, but i get here by googling ways to unarchive some tricky zip files, hope it helps someone.
